// strategyPortfolio.config.js
// Single source of truth for the stocks-only portfolio strategy configuration.

const StrategyPortfolioConfig = {
  market: "stocks",
  universe: {
    source: "iex",
    filters: {
      priceMin: 5,
      priceMax: 500,
      advDollarMin: 25000000,
      advDollarMinUpper: 40000000,
      advDollarMinLower: 15000000,
      avgShareVolumeMin: 1500000,
      atrPctMin: 1.0,
      atrPctMax: 6.0,
      spreadPctMax: 0.2,
      useSpreadProxy: false,
      excludeEtf: true,
      excludeLeveragedEtf: true,
      excludePenny: true,
      excludeOtc: true,
      excludeHalted: true,
      excludeKeywords: ["UP", "DOWN", "BULL", "BEAR", "2X", "3X"],
      universeTargetMin: 300,
      universeTargetMax: 800,
      barLookbackDays: 20,
      batchSize: 200,
    },
  },
  timeframesAllowed: ["15m", "1h", "4h"],
  globalRisk: {
    maxTotalPositions: 12,
    maxOpenRiskPct: 2.0,
    dailyStopPct: 2.5,
  },
  layers: [
    {
      id: "CORE",
      name: "Core",
      allocationPct: 0.45,
      maxOpenPositions: 6,
      maxRiskPerTradePct: 0.5,
      lossStopDailyPct: 1.25,
      lossStopWeeklyPct: 3.0,
      cooldownHoursAfterStop: 6,
      entryPresetId: "CORE_TREND",
      exitPresetId: "CORE_EXIT",
      timeframe: "4h",
    },
    {
      id: "SWING",
      name: "Swing",
      allocationPct: 0.4,
      maxOpenPositions: 8,
      maxRiskPerTradePct: 0.35,
      lossStopDailyPct: 1.0,
      lossStopWeeklyPct: 2.5,
      cooldownHoursAfterStop: 6,
      entryPresetId: "SWING_PULLBACK",
      exitPresetId: "SWING_EXIT",
      timeframe: "1h",
    },
    {
      id: "AGGR",
      name: "Aggressive",
      allocationPct: 0.15,
      maxOpenPositions: 4,
      maxRiskPerTradePct: 0.2,
      lossStopDailyPct: 0.6,
      lossStopWeeklyPct: 1.5,
      cooldownHoursAfterStop: 8,
      entryPresetId: "AGGR_BREAKOUT",
      exitPresetId: "AGGR_EXIT",
      timeframe: "15m",
      defaultEnabled: false,
    },
  ],
  entryPresets: {
    CORE_TREND: {
      name: "Core Trend",
      emaFast: 50,
      emaSlow: 200,
      adxPeriod: 14,
      adxMin: 18,
      rsiPeriod: 14,
      rsiMin: 45,
      rsiMax: 70,
      pullbackToEma: true,
    },
    SWING_PULLBACK: {
      name: "Swing Pullback",
      emaFast: 20,
      emaSlow: 100,
      rsiPeriod: 14,
      rsiMin: 40,
      rsiMax: 60,
      atrPeriod: 14,
      atrPctMin: 1.0,
      atrPctMax: 4.5,
      swingLookback: 20,
      pullbackMinPct: 0.8,
      pullbackMaxPct: 3.0,
    },
    AGGR_BREAKOUT: {
      name: "Aggressive Breakout",
      emaPeriod: 20,
      rsiPeriod: 14,
      rsiMin: 55,
      rsiMax: 75,
      breakoutLookback: 20,
      volumeMultiplier: 1.8,
      volumeMaPeriod: 20,
    },
  },
  exitPresets: {
    CORE_EXIT: {
      name: "Core Exit",
      atrPeriod: 14,
      initialAtrMult: 1.8,
      trailStartR: 2.0,
      trailAtrMult: 2.5,
      trendExitFastEma: 50,
      trendExitSlowEma: 200,
      useTakeProfit: false,
    },
    SWING_EXIT: {
      name: "Swing Exit",
      atrPeriod: 14,
      initialAtrMult: 1.2,
      takeProfitR: 2.2,
      trailStartR: 1.2,
      trailAtrMult: 1.4,
      timeStopBars: 18,
      timeStopMinR: 0.6,
    },
    AGGR_EXIT: {
      name: "Aggressive Exit",
      atrPeriod: 14,
      initialAtrMult: 0.9,
      takeProfitR: 1.6,
      trailStartR: 0.8,
      trailAtrMult: 1.0,
      invalidationBars: 3,
    },
  },
  regimeRules: {
    TREND: ["CORE", "SWING"],
    RANGE: ["SWING"],
    VOLATILE: ["AGGR"],
    OFF: [],
  },
  regimeConfig: {
    emaFast: 50,
    emaSlow: 200,
    adxPeriod: 14,
    adxTrendMin: 18,
    adxChopMax: 16,
    atrPeriod: 14,
    atrPctHigh: 1.2,
  },
  slippageModel: {
    type: "atrPct",
    pct: 0.1,
  },
};

module.exports = { StrategyPortfolioConfig };
